### ISSUE TITLE
is there a guide, demo or documentaion?

### ISSUE THREAD

**Issue by dicoriomri** [ionic-team/capacitor-plugin-http#5]
Hi,
Thanks for the awsome work :)

Is there a guide, demo or documentaion on how to use this in VUE or Angular?

Thanks again

**Comment by tutchmedia** [comment]
I don't think anything is available as of yet but here is how I'm using it in Angular:

```
import { Http } from '@capacitor/http';
return await Http.request({
      url:'https://....',
      method: 'POST',
      data: {
           "username":"test",
           "password": "test123"
        }
      },
      headers: {
        'Content-Type': 'application/json'
      }
});
```

**Comment by jongbonga** [comment]
```
import { Plugins } from '@capacitor/core';
const Http = Plugins.Http;
```

Instead of;
`import { Http } from '@capacitor/http';`

See [here](https://github.com/ionic-team/capacitor-plugin-http/issues/6#issuecomment-628841710)

**Comment by mlynch** [comment]
Just added usage docs to the README. Cheers!
