### ISSUE TITLE
Plugin always runs web code, even on native device

### ISSUE THREAD

**Issue by curthusting** [ionic-team/capacitor-plugin-http#6]
Maybe my implementation is incorrect, but I am unable to run native code when trying to test out the new plugin.
Packages
```
"@ionic/angular": "^5.1.0",
"@capacitor/core": "^2.1.0",
"@capacitor/http": "0.0.2",
```
Implementation
```
import { Http } from "@capacitor/http";
  async testDownload() {
    const download = await Http.downloadFile({
      url: "https://cdn.jwplayer.com/videos/8L4m9FJB-Zq6530MP.mp4",
      filePath: `download`,
      fileDirectory: FilesystemDirectory.Cache
    })
  }
```
I also added logging to both the web code and the native plugins, and when I test the download, it always hits the web plugin js...

**Comment by jwuliger** [comment]
Hello, my team is having the same issue. Is this something that was missed?

**Comment by curthusting** [comment]
@jwuliger I think I figured out how to get it to load the native code...although I still need to run more testing on it...I am not sure if this will be the "new" way to include capacitor plugins, but have your team try this;
```
import { Plugins } from '@capacitor/core';

const Http = Plugins.Http;
```
Instead of;
`import { Http } from '@capacitor/http';`

**Comment by mlynch** [comment]
Hi all, apologies for the confusion here. There will likely be two things required:

First, to make sure the web functionality does load, you need to import the package at least once:

```typescript
import '@capacitor/http`
```

Then, as closely as possible before using the plugin, access it from the `Plugins` object:

```typescript
const doThing = () => {
  const { Http } = Plugins;
  // ...
}
```
